# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    identifier: osImW0bE
    url: /
    weight: 10
  - name: Present Position
    identifier: eTEzTuY1
    url: presentposition/
    weight: 20
  - name: Career Summary
    identifier: DgbGb4Bf
    url: careersummary/
    weight: 30
  - name: Certifications
    identifier: cJSWv8kL
    url: certifications/
    weight: 40    
  - name: Projects
    identifier: BhjikZTE
    url: projects/
    weight: 50

